# fly.toml app configuration file generated for fly-deployment-latency on 2023-11-08T13:16:27-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-deployment-latency"
primary_region = "sea"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
